### ISSUE TITLE
tls/ssl configs

### ISSUE THREAD

**Issue by chrisdrew1** [jadestorm/puppet-patroni#1]
The module doesn't seem to have a way to add key,cert,cacert into the config yaml.  Can you add that?

**Comment by jadestorm** [comment]
Howdy!  I'm not actively using Patroni anymore so while I can add it -- I won't be able to test it.  If you would be down to test it after it's added, sure.  That said, I'm having trouble finding any docs on it -- can you provide a sample config and/or link to the documentation?

**Comment by jadestorm** [comment]
(if you would rather take a whack at it and submit a PR I'd be happy to look at that as well!)

**Comment by chrisdrew1** [comment]
Thanks.  I found the err in my ways.  etcd_key instead of key once I dug into your manifests..
